#!/usr/bin/env python3
"""Build the Yoin icon set.

    cd docs/icons && python3 build.py

Writes
  docs/icons/svg/yoin_<name>.svg                       editable SVG, currentColor, 1.5 stroke
  docs/icons/icons.json                                 metadata + markup for the preview page
  app/src/main/res/drawable/ic_yoin_<name>.xml          Android VectorDrawable (black, tinted by Icon)

Requires: python3, shapely (pip install shapely) for the knockout helper.
Sources live in docs/icons/src/: geom.py (path kit), knock.py (stroke knockouts),
registry.py and icons_*.py (one function per icon).
"""
from __future__ import annotations

import html
import importlib
import json
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "src" if (HERE / "src").exists() else HERE
sys.path.insert(0, str(SRC))

from geom import to_d  # noqa: E402
from registry import ORDER, REGISTRY, svg_markup  # noqa: E402

for mod in ("icons_nav", "icons_music", "icons_devices", "icons_content"):
    importlib.import_module(mod)

GROUP_ZH = {"nav": "导航与通用", "music": "播放与音乐", "content": "内容与笔记", "device": "设备与服务"}

HEADER = "Yoin icon set · Luminous edition · generated by docs/icons/build.py — edit the sources, not this file"


def svg_file(ic) -> str:
    body = svg_markup(ic, size=24, title=True)
    return f"<!-- {HEADER} -->\n" + body + "\n"


def vd_file(ic) -> str:
    out = [
        '<?xml version="1.0" encoding="utf-8"?>',
        f"<!-- {HEADER} -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="24dp"',
        '    android:height="24dp"',
        '    android:viewportWidth="24"',
        '    android:viewportHeight="24">',
    ]
    cur = None
    indent = "    "
    for ly in ic.layers:
        g = ly.get("group")
        if g != cur:
            if cur is not None:
                out.append("    </group>")
            if g is not None:
                out.append(f'    <group android:name="{g}">')
            cur = g
        ind = indent * (2 if g else 1)
        attrs = []
        if ly.get("id"):
            attrs.append(f'android:name="{ly["id"]}"')
        attrs.append(f'android:pathData="{to_d(ly["d"])}"')
        mode = ly["mode"]
        if mode in ("stroke", "fillstroke"):
            attrs += [
                'android:strokeColor="#FF000000"',
                'android:strokeWidth="1.5"',
                'android:strokeLineCap="round"',
                'android:strokeLineJoin="round"',
            ]
        if mode in ("fill", "fillstroke"):
            attrs.append('android:fillColor="#FF000000"')
            if ly.get("rule") == "evenodd":
                attrs.append('android:fillType="evenOdd"')
        else:
            attrs.append('android:fillColor="#00000000"')
        out.append(f"{ind}<path")
        for i, a in enumerate(attrs):
            end = " />" if i == len(attrs) - 1 else ""
            out.append(f"{ind}    {a}{end}")
    if cur is not None:
        out.append("    </group>")
    out.append("</vector>")
    return "\n".join(out) + "\n"


def main(repo_root: Path | None = None):
    repo_root = repo_root or HERE.parent.parent
    svg_dir = HERE / "svg"
    svg_dir.mkdir(exist_ok=True)
    drawable = repo_root / "app" / "src" / "main" / "res" / "drawable"
    write_drawables = drawable.exists()
    meta = []
    for name in ORDER:
        ic = REGISTRY[name]
        if ic.group == "lab":
            continue
        (svg_dir / f"yoin_{name}.svg").write_text(svg_file(ic), encoding="utf-8")
        if write_drawables:
            (drawable / f"ic_yoin_{name}.xml").write_text(vd_file(ic), encoding="utf-8")
        meta.append(
            dict(
                name=name,
                zh=ic.zh,
                group=ic.group,
                groupZh=GROUP_ZH.get(ic.group, ic.group),
                replaces=ic.replaces,
                note=ic.note,
                svg=svg_markup(ic, size=24, title=False, ids=False),
            )
        )
    (HERE / "icons.json").write_text(json.dumps(meta, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"{len(meta)} icons -> {svg_dir}" + (f" and {drawable}" if write_drawables else " (no drawable dir found)"))


if __name__ == "__main__":
    root = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else None
    main(root)
